namespace spotify_breakdown_playlists_cppwinrt
{
    [default_interface]
    runtimeclass Methods : Windows.UI.Xaml.Controls.Page
    {
        Methods();

		Windows.UI.Xaml.Media.Imaging.BitmapImage CoverImage{ get; };
    }
}
