namespace spotify_breakdown_playlists_cppwinrt
{
    [default_interface]
    runtimeclass Methods_Methods : Windows.UI.Xaml.Controls.Page
    {
        Methods_Methods();
        Windows.Foundation.Collections.IObservableVector<IInspectable> MethodNames{ get; };
    }
}
