namespace spotify_breakdown_playlists_cppwinrt
{
	runtimeclass Playlist : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        Playlist();
		Playlist(String itemJson);
		String Name{ get; };
		Windows.UI.Xaml.Media.Imaging.BitmapImage Thumbnail{ get; };
		String SongCount{ get; };
    }
}
