namespace spotify_breakdown_playlists_cppwinrt
{
	runtimeclass Source : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        Source();
		Source(String itemJson);
		String Name{ get; };
		Windows.UI.Xaml.Media.Imaging.BitmapImage Thumbnail{ get; set; };
		String SongCount{ get; };
		String TracksUri{ get; };
    }
}
